name: LaTeX build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build_latex:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
